title: FCV Slide Deck Analytics
author: Miguel Purroy

repository:
  url: https://github.com/mglpurroy/slide-deck-analytics-1
  branch: main

# Enable notebook execution
execute:
  execute_notebooks: "auto"