repository:
  url: https://github.com/mglpurroy/slide-deck-analytics-1  # Replace with your actual GitHub repo
  branch: main  # Change this if your main branch is different
html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true