# Book settings
title: FCV Slide Deck Analytics
author: Miguel Purroy

repository:
  url: https://github.com/mglpurroy/slide-deck-analytics-1  # Replace with your actual GitHub repo
  branch: main  # Change this if your main branch is different

execute:
  execute_notebooks: "auto" 
  allow_errors: true  # Prevents build crashes

html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  remove_code_source: true
  use_jupyterlab: true  # Enables Jupyter widgets & interactive figures 
  use_thebe: true

sphinx:
  extra_extensions:
    - sphinx_copybutton  # Enables copy button
    - sphinx_design  # Improves figure rendering
    - sphinx_thebe  # Enables live notebook execution